---
# tasks file for ldap-oauth

- name: Create CA cert configmap
  k8s:
    validate_certs: no
    state: present
    definition: "{{ lookup('template', 'templates/ca-cert-cfgmap.j2') }}"
  tags:
    - ldap-ca

- name: Create LDAP bind password secret
  k8s:
    validate_certs: no
    state: present
    definition: "{{ lookup('template', 'templates/bind-password-secret.j2') }}"

- name: Create LDAP oauth config
  k8s:
    validate_certs: no
    state: present
    definition: "{{ lookup('template', 'templates/ldap-oauth-config.j2') }}"
