---
- name: Ansible playbooks to test k8s
  gather_facts: false
  hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:

  - name: 01 create namespace
    k8s:
      name: k8s-test-ns
      api_version: v1
      kind: Namespace
      state: present
