apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
   requests:
     storage: "{{ image_registry_size }}"
  storageClassName: "{{ image_registry_storage_class }}"
