---
# tasks file for etcd-encyption

- name: Patch apiserver resource to enable etcd encryption
  k8s:
    validate_certs: no
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: APIServer
      metadata:
        name: cluster
      spec:
        encryption:
          type: aescbc
  when:
    - enable_etcd_encryption is defined
    - enable_etcd_encryption | bool
  tags:
    - etcd_encryption
