- name: Add infra role to the nodes that have infra initials in its name
  k8s:
    validate_certs: no
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ item.metadata.name }}"
        labels:
          node-role.kubernetes.io/infra: ""
  when:
    - item.metadata.name | regex_search( infra_nodes_tag + '[0-9]' | string)
    - item["metadata"]["labels"]["node-role.kubernetes.io/infra"] is not defined
  loop_control:
    label: "{{ item.metadata.name }}"
  loop: "{{ ocp_nodes.resources }}"


- name: Remove worker node role from the infra nodes
  command: "{{ oc_binary }} label node {{ item.metadata.name }} node-role.kubernetes.io/worker-"
  when:
    - item.metadata.name | regex_search( infra_nodes_tag + '[0-9]' | string)
    - item["metadata"]["labels"]["node-role.kubernetes.io/worker"] is defined
  loop_control:
    label: "{{ item.metadata.name }}"
  loop: "{{ ocp_nodes.resources }}"
