---
# Prepare Image Registry

- name: get config for imageregistry
  k8s_info:
    validate_certs: no
    api_version: imageregistry.operator.openshift.io/v1
    kind: Config
    name: cluster
  register: reg_imagecfg

# Configure PVC storage
- name: Configure PVC storage for Image Registry
  k8s:
    validate_certs: no
    state: present
    definition: "{{ lookup('template', 'templates/registry-pvc.yaml') }}"
  when:
    - reg_imagecfg['resources'][0]['spec']['storage']['claim'] is undefined

- name: Update registry config with PVC, rolloutStrategy, replicas, Managed mode, and move to infra nodes
  k8s:
    validate_certs: no
    state: present
    definition:
      apiVersion: imageregistry.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        managementState: Managed
        rolloutStrategy: Recreate
        replicas: 1
        storage:
          pvc:
            claim: image-registry-storage
        nodeSelector:
          node-role.kubernetes.io/infra: ""
