---
- name: Create OpenShift Manifest
  shell: |
    /usr/local/bin/openshift-install --dir {{ deployment_directory }} create manifests
  tags: manifests

- name: Ensure the manifests directory is owned by {{ ansible_user }}
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
  - "{{ deployment_directory }}/openshift"
  - "{{ deployment_directory }}/manifests"
  tags: manifests
