---
# defaults file for prepare-install
bastion_http_port: 8080
ignition_roles:
  - bootstrap
  - master
  - worker
ignition_files_web_path: "/var/www/html/ignition"

deployment_directory: "/home/{{ ansible_user_id }}/ocp"

clock_servers:
  - 1.2.3.4

hyperthreading: "Enabled"

base_domain: "example.com"
cluster_name: "ocp4"
network_type: "OpenShiftSDN"
machine_cidrnet: "10.238.128.0/23"
cluster_cidrnet: "10.254.0.0/16"
cluster_hostprefix: "24"
service_cidrnet: "172.30.0.0/16"
sdn_mtu: 1450
vxlan_port: 4888

http_proxy: "http://proxy-ip:3128"
https_proxy: "http://proxy-ip:3128"

vcenter_url: vcenter.example.com
vcenter_username: vcenter-service-account
vcenter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256

vcenter_datacenter: "datacenter-name"
vcenter_datastore: "Vcenter-Datastore"
vcenter_folder: "ocp4"

catrustbundle: |
  -----BEGIN CERTIFICATE-----
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  -----END CERTIFICATE-----

pullsecret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
