== ldap-oauth

=== Setting up LDAP oAuth in OpenShift 4.x

The ldap-oauth role handles configuring the default identity provider for the
cluster. An OCP cluster can have multiple identity providers eg: LDAP oAuth and
a htpasswd file, for instance.

NOTE: This role in its current state will overwrite or blow away any other
oAuth providers that are configured.

=== Role Variables
Default role variables that are defined and should be changed

----
ldap_provider_name: 'LDAP-name'
ldap_bind_user: 'bind-DN-user'
ldap_bind_password: 'bind-password-encrypted'
ldap_url: 'ldaps://ad1.office.example.com/OU=Staff,DC=office,DC=example,DC=com?sAMAccountName'
----

ldap_bind_user::
  ldap bind user used to make connect to the AD to validate users
ldap_bind_password::
  ldap user's password to authenticate against AD
ldap_url::
  specify the ldap URL including the OU under which all end users are listed.
  the playbooks will use secure LDAP irrespective of weather you use ldap or
  ldaps. If you want to to use insecure LDAP, you need to edit the ldap oauth
  template.

files/ldap-ca-cert.txt::
  This file should contain the root ca cert for the internal or external CA
  that signed the LDAP server's certificate. This Readme attempts to walk you
  through extrating the RootCA cert for you LDAP endpoint. *Attempts!*.

=== Example Usage
No point in including this role and passing a ton of variables. This role was
never written to be used out of the box anyways. There is a root an ldap ca
cert file ldap-ca-cert.txt, whose contents have to be replaced with your own.

So no example usage.

