---
# tasks file for ingress-tls-cert

- name: Create secret for holding ingress ssl cert
  k8s:
    validate_certs: no
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/tls
      metadata:
        name: "{{ ocp_cluster_name }}-apps-cert"
        namespace: openshift-ingress
      data:
        tls.crt: "{{ ingress_certs | b64encode }}"
        tls.key: "{{ ingress_key | b64encode }}"
  tags:
    - ingress-cert
    - tls

- name: Patch the default ingress router
  k8s:
    validate_certs: no
    state: present
    definition:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec:
        defaultCertificate:
          name: "{{ ocp_cluster_name }}-apps-cert"
        replicas: 3
  tags:
    - ingress-cert
    - tls
